services:
  terraform-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform-container
    volumes:
      - ./data:/workspace
      - terraform_aws_credentials:/root/.aws
    # env_file:
    #   - .env
    working_dir: /workspace
    entrypoint: ["/bin/sh"]
    stdin_open: true
    tty: true
    networks:
      - shared_network

networks:
  shared_network:
    name: intent_recognition_localstack_network
    external: true

volumes:
  terraform_aws_credentials: